### ISSUE TITLE
task breakdown

### ISSUE THREAD

**Issue by lucashakewill** [jdoodle-ai/Todo-App3#122]
help me break down tasks. When I click the button with class "ai-button" (this already exists), send a request to OpenAI API to break down the task into 3-8 manageable steps. Save the result in the existing "task description" field. My API key is in the OS environment vairable. Make sure you use gpt-4o-mini, chat completions endpoint and use python requests library to make the api call. Change only the python and html files.

**Comment by jdoodle-ai** [comment]
Pulled Repository content

**Comment by jdoodle-ai** [comment]
Solution plan is created
